frontend:
	bash components/frontend.sh

catalogue:
	bash components/catalogue.sh

mongodb:
	bash components/mongodb.sh

redis:
	bash components/redis.sh 

user:
	bash components/user.sh 

cart:
	bash components/cart.sh